title: "Martin Gude"
name: "Martin Gude"
markdown: kramdown
exclude: ["README.md", "/Gemfile", "/Gemfile.lock", "CNAME"]

collections:
  pages:
    output: true
    permalink: "/:path.html"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-tidy

sass:
  style: compressed
theme: jekyll-theme-cayman

jekyll_tidy:
  ignore_env: development
  compress_html: true  